#!/usr/bin/python

def build(bld):
    bld(features = 'cxx cprogram',
        source = ['test.cc'],
        target = 'classifier_test',
        includes = bld.SRCPATH,
        linkflags = ['-O2'],
        use = ['classifiers'])
