#!/usr/bin/python

def build(bld):
    bld.shlib(source = ['nb.cc'],
              target = 'naivebayes',
              includes=bld.SRCPATH)

    bld(features = 'cxx cprogram',
        source = ['nb_test.cc'],
        target = 'nb_test',
        includes = bld.SRCPATH,
        use = ['naivebayes'])
