#!/usr/bin/python

def build(bld):
    bld.shlib(source = ['hinge.cc'],
              target = 'subgradient_hinge',
              includes=bld.SRCPATH)

    bld(features = 'cxx cprogram',
        source = ['subgradient_test.cc'],
        target = 'subgradinet_test',
        includes = bld.SRCPATH,
        use = ['subgradient_hinge'])
