#!/usr/bin/python

def build(bld):
    bld.shlib(source = ['cw.cc'],
              target = 'cw',
              includes=bld.SRCPATH)

    bld(features = 'cxx cprogram',
        source = ['cw_test.cc'],
        target = 'cw_test',
        includes = bld.SRCPATH,
        use = ['cw'])
