#!/usr/bin/python

def build(bld):
    bld.shlib(source = ['perceptron.cc'],
              target = 'perceptron',
              includes=bld.SRCPATH)

    bld.shlib(source = ['averaged_perceptron.cc'],
              target = 'averaged_perceptron',
              includes=bld.SRCPATH)

    bld(features = 'cxx cprogram',
        source = ['perc_test.cc'],
        target = 'perc_test',
        includes = bld.SRCPATH,
        use = ['perceptron'])

    bld(features = 'cxx cprogram',
        source = ['av_perc_test.cc'],
        target = 'av_perc_test',
        includes = bld.SRCPATH,
        use = ['averaged_perceptron'])
