#!/usr/bin/python

def build(bld):
    bld.shlib(source = ['complement_nb.cc'],
              target = 'complement_nb',
              includes=bld.SRCPATH,
              use = ['naivebayes'])

    bld(features = 'cxx cprogram',
        source = ['complement_nb_test.cc'],
        target = 'complement_nb_test',
        includes = bld.SRCPATH,
        use = ['complement_nb'])
