#!/usr/bin/python

def build(bld):
    bld.shlib(source = ['naivebayes/nb.cc',
                        'complement_nb/complement_nb.cc',
                        'perceptron/perceptron.cc',
                        'perceptron/averaged_perceptron.cc',
                        'passive_aggressive/pa.cc',
                        'confidence_weighted/cw.cc',
                        'subgradient/hinge.cc',
                        'fobos/fobos.cc',
                        'fobos/cumulative_fobos.cc',
                        ],
              target = 'classifiers',
              includes=bld.SRCPATH)

    bld.recurse('test')
